version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    restart: always

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:password@db:5432/app
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq
      JWT_SECRET: your_jwt_secret
    restart: always

  assistant:
    build: ./assistant
    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    restart: always

volumes:
  pg_data:
