name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults: { run: { shell: bash } }
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd services/api
          npm ci

      - name: Lint & format check
        run: |
          cd services/api
          npm run lint
          npm run prettier:check

      - name: Run tests
        run: |
          cd services/api
          npm test

      - name: Build Docker image
        run: |
          cd services/api
          docker build -t travel-api:ci .
